### ISSUE TITLE
404 error for doc links in README

### ISSUE THREAD

**Issue by z11i** [se-edu/addressbook-level25#15]
The relative links of "Useful Links" in the README are successfully replaced when [viewed alone](https://github.com/se-edu/addressbook-level3/blob/master/README.md), **doc/UserGuide.md** becomes https://github.com/se-edu/addressbook-level3/blob/master/doc/UserGuide.md, which is correct.

However when viewed from the repo's [main page](https://github.com/se-edu/addressbook-level3), **doc/UserGuide.md** becomes https://github.com/se-edu/doc/UserGuide.md, which results in a **404 Not Found** error

Can anyone else confirm this behavior? It appears that [addressbook-level2](https://github.com/se-edu/addressbook-level2#addressbook-level-2) also has this issue. Other repos are behaving normally, such as [HubTurbo](https://github.com/HubTurbo/HubTurbo).

**Comment by damithc** [comment]
This is a regression on GitHub side that surfaced today. I've reported it to them. All repos using relative links are affected e.g. TEAMMATES. HubTurbo is not affected because it is using absolute links.

**Comment by z11i** [comment]
I suspect that this is a GitHub bug. Which is weird is that HubTurbo uses relative link for one, and it is okay. I'll close this as this is not suitable for here then.

**Comment by damithc** [comment]
They have fixed the problem.
