### ISSUE TITLE
If StorageStub.save() does nothing, test cases will fail

### ISSUE THREAD

**Issue by yamgent** [se-edu/addressbook-level25#27]
From LearningOutcomes.md:

> - Implement the `StorageStub` such that calls to the `save` method do nothing (i.e. empty method body).

Since some of the test cases uses a non-empty `AddressBook`, `LogicTest.assertCommandBehavior(...)` will try to compare the expected non-empty `AddressBook`, with the `AddressBook` 'residing' on the storage (which is empty since the method does not attempt to retain the content in any way), resulting in failing test cases.

Please advise.

**Comment by damithc** [comment]
`LogicTest` should no longer compare the actual stored data with expected stored data. As we are now using a `StorageStub` that does nothing, it doesn't make sense to check if the data was stored properly.

**Comment by yamgent** [comment]
Ah that makes sense... thank you! :)
