### ISSUE TITLE
data/ in .gitignore cause changes to seedu.addressbook.data package to be ignored

### ISSUE THREAD

**Issue by ZhangYiJiang** [se-edu/addressbook-level25#34]
To reproduce: 
- Open a terminal in the `src/seedu/addressbook/data` folder 
- `touch test` to create a new file 
- `git status` - notice git did not track the newly created file 

This is caused by the `data/` line in the `.gitignore` file. If the intention was to ignore the data directory at the root, `/data/` should be used instead. In addition, if this was a file local only to a single developer, it might be better to add it to `.git/info/exclude` instead

**Comment by damithc** [comment]
Thanks for the bug report @ZhangYiJiang
