### ISSUE TITLE
executable jar file doesn't run

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level25#39]
Some students have reported that the executable jar file created by eclipse doesn't run on Windows but runs on Mac. The app runs within the IDE though.

**Comment by damithc** [comment]
@yl-coder @m133225 any idea?

**Comment by yl-coder** [comment]
@yijin can help to try this on windows? Open the jar via cmd prompt and paste the stack trace here.

On 28 Oct 2016 19:29, "Damith C. Rajapakse" notifications@github.com wrote:

@yl-coderhttps://github.com/yl-coder @m133225https://github.com/m133225 any idea?

##

**Comment by damithc** [comment]
Looks like the jar file cannot load the fxml file (Gui.java). 
This may be relevant. http://stackoverflow.com/questions/24841062/javafx-resource-cannot-be-loaded-when-running-from-jar
