### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by damithc** [se-edu/addressbook-level25#4]
Add logging, preferably with a rolling log file. 
Perhaps limit to a few levels: DEBUG, INFO, WARNING, ERROR?

**Comment by damithc** [comment]
@m133225 can do this one?

**Comment by damithc** [comment]
I think we can postpone this for level 4

**Comment by m133225** [comment]
Just a note, default logger has `SEVERE`, `WARNING`, `INFO`, `CONFIG`, `FINE`, `FINER`, `FINEST` instead of log4j's alternatives of `ERROR`, `FATAL`, `WARN`, `INFO`, `DEBUG` and `TRACE`. I think just keeping the levels that the default logger has should be fine (and complicates the code less).

**Comment by damithc** [comment]
Good point @m133225 Let's keep the default levels.
