### ISSUE TITLE
Make package/directory structure similar to Level 4

### ISSUE THREAD

**Issue by pyokagan** [se-edu/addressbook-level25#60]
While the directory/package structure does not have to be *exactly* the same, it is still beneficial for the overall project if they are as similar to each other as possible to ease porting of code from one level to another.

## Directory structure

Making them the same would allow us to share the `build.gradle` file between levels (for e.g. CI )

* Main sources should be moved to `src/main/java`.

* Test sources should be moved to `src/test/java`.

## Package naming

Having consistent package names will make it easier to port code from one level to another. It will also make it clear that different levels *build upon* each other.

* `seedu.addressbook` should be renamed to `seedu.address`.

    * `Main` should be renamed to `MainApp`.

* `seedu.addressbook.common` should be renamed to `seedu.address.commons`.

* `seedu.addressbook.data` should be renamed to `seedu.address.model`.

* `seedu.addressbook.data.exception` should be renamed to `seedu.address.commons.exceptions`.

* `seedu.addressbook.commands` should be renamed to `seedu.address.logic.commands`.

* `seedu.addressbook.parser` should be renamed to `seedu.address.logic.parser`.

**Comment by pyokagan** [comment]
@damithc Thoughts?

**Comment by damithc** [comment]
Yes, it's a good idea @pyokagan
